spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ProductsMarket?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
